// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompressorClient is the client API for Compressor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompressorClient interface {
	Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error)
}

type compressorClient struct {
	cc grpc.ClientConnInterface
}

func NewCompressorClient(cc grpc.ClientConnInterface) CompressorClient {
	return &compressorClient{cc}
}

func (c *compressorClient) Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error) {
	out := new(CompressResponse)
	err := c.cc.Invoke(ctx, "/proto.Compressor/Compress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompressorServer is the server API for Compressor service.
// All implementations should embed UnimplementedCompressorServer
// for forward compatibility
type CompressorServer interface {
	Compress(context.Context, *CompressRequest) (*CompressResponse, error)
}

// UnimplementedCompressorServer should be embedded to have forward compatible implementations.
type UnimplementedCompressorServer struct {
}

func (UnimplementedCompressorServer) Compress(context.Context, *CompressRequest) (*CompressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compress not implemented")
}

// UnsafeCompressorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompressorServer will
// result in compilation errors.
type UnsafeCompressorServer interface {
	mustEmbedUnimplementedCompressorServer()
}

func RegisterCompressorServer(s grpc.ServiceRegistrar, srv CompressorServer) {
	s.RegisterService(&Compressor_ServiceDesc, srv)
}

func _Compressor_Compress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressorServer).Compress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Compressor/Compress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressorServer).Compress(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Compressor_ServiceDesc is the grpc.ServiceDesc for Compressor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compressor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Compressor",
	HandlerType: (*CompressorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compress",
			Handler:    _Compressor_Compress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compressor.proto",
}
