name: pipeline
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ROOT: /home/runner/work/compressrv/compressrv
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: install required packages
        run: |
          sudo apt update
          sudo apt install ffmpeg
      - name: Run Unit Tests
        run: go test -v ./...